### ISSUE TITLE
Accept changes of 'Max Local Anchors' during runtime

### ISSUE THREAD

**Issue by zantiu** [microsoft/MixedReality-WorldLockingTools-Unity#112]
Now runtime changes to 'Max Local Anchors' on the WorldLockingManager are not taken into account.
Is it possible to allow programmatical changes to this number during runtime?
(No need to add a special UI)
And when the new number is lower immediately remove the necessary amount of anchors?

This would be useful for our performance tests in big areas and find a balance with the rest of our application.

**Comment by fast-slow-still** [comment]
You can directly set the `int MaxLocalAnchors` property on the IAnchorManager interface, e.g. `WorldLockingManager.GetInstance().AnchorManager.MaxLocalAnchors = newMaxCount`. That will take immediate effect, and remain in effect until overriden by a setting a new WorldLockingContext.

As the system is now, after lowering the MaxLocalAnchors count below the current number of anchors, one anchor per frame will be deleted until the number of anchors is back under the limit. This helps provide stability to the system, as well as smoothing performance. Changing that to immediately remove the excess would be high risk, so won't happen without further study.

Since you know the framerate, and you know that one anchor will be dropped per frame, could you put a delay in your performance test between measurement before and after changing the MaxLocalAnchors? For example, a one second delay would allow stabilization after lowering MaxLocalAnchors by up to 60.

**Comment by fast-slow-still** [comment]
By the way, I agree that setting the MaxLocalAnchors on the WLT Manager should immediately propagate to the AnchorManager. The above suggestions are intended to unblock you now, rather than suggest no changes in the WLT code are needed. Thanks!

**Comment by zantiu** [comment]
Ok that works for us!
