### ISSUE TITLE
[Question] How is interpolation of space pins calculated?

### ISSUE THREAD

**Issue by camnewnham** [microsoft/MixedReality-WorldLockingTools-Unity#116]
We've been experimenting with WLT with the following setup:

- 3D scan of a space (large, around 20mx50m, but with repeated columns)
- Set up QR codes at known locations based on point cloud scan, <10mm placement error
- Create space pins (`SpacePinOrientable`) registering (and updating) the QR code locations
- Visualize (decimated) point cloud scan to manually/optically see the deviation from the physical

Our initial assumption was that interpolation would be based on the _position_ of the HoloLens relative to the physical location of the QR codes (space pins) in either a weighted or linear ([docs](https://microsoft.github.io/MixedReality-WorldLockingTools-Unity/DocGen/Documentation/Concepts/Advanced/SpacePins.html#interpolation)) fashion. However, what we have noticed is that there's significant movement/compensation/interpolation which _appears_ to be based on the orientation of the headset. To provide an example:

Each number represents a QR code & space pin placed at a measured location on a column. The red represents a user and arbitrary FOV.

![image](https://user-images.githubusercontent.com/19278856/107182349-ab4f2f80-6a30-11eb-8d88-756d5e1c2133.png)
1. This position, shows the frozen space and QR (4) code appear very close.

![image](https://user-images.githubusercontent.com/19278856/107182389-c326b380-6a30-11eb-94ee-8f37d5ee0038.png)
2. Rotating the head without changing position appears results in clearly visible interpolation of the digital position. The digital (4) shifts a significant distance from the physical in a repeatable interpolation (rotating head back and forth re-plays the interpolation).

![image](https://user-images.githubusercontent.com/19278856/107182522-04b75e80-6a31-11eb-876a-46921bedc452.png)
3. Standing on the other side of the column shows the digital in the correct location (as per the docs there is no extrapolation when outside the space pin boundary, so this makes sense).

Based on this we concluded that the orientation of the headset (which space pins are in FOV and/or which feature points are in FOV) affects the interpolation. The logic for this would be reasonable - make the space pins that are being _looked at _ appear correct rather than a space pin that is behind you... However we are interested in having some more control over the weighting here, as the user may be looking at a hologram immediately in-front of them even if there's a space-pin in the distance.

So the short question is: Does the users facing direction affect the interpolation? 
The longer one is: If so, how is this weighted with the device position, and is there any way to control this?

**Comment by fast-slow-still** [comment]
Short answer is, no, the user's facing direction is not fed into the interpolation, the interpolator operates on horizontal position only.

The exact location of the head/device is not necessarily intuitively obvious. It is quite possible that rotating the head is actually moving the device in an arc around the axis of rotation. 

It also looks like the device is approximately sitting on an "edge" in the interpolation mesh, so slight movements might have it crossing the edge, and so shifting from interpolation of one triangle, say 3,4,6, to another triangle, say 3,4,2. Normally this isn't an issue, because all of the SpacePins should be saying basically the same thing. Also, the interpolation is smooth and continuous, even if it can be abrupt when interpolating between to very different poses across a small distance.

One thing that might be useful. If you haven't already, you might try using the SpacePinVisualizer prefab (in WorldLocking.Tools/Prefabs). There's a sample use in [this WLT Sample](https://microsoft.github.io/MixedReality-WorldLockingTools-Samples/Advanced/AlignSubScene/AlignSubScene.html#twoindependentspacesunity). The SpacePinVisualizer is a community submission. It's a little rough, but I think brilliant and very useful. Let me know if you have any trouble with it, but it's pretty much drag and drop.

I would be very interested to hear back if the SpacePinVisualizer suggests anything.

Also, one last question, what is the scale of your setup? I.e. what is the distance between points 3 and 4?

**Comment by camnewnham** [comment]
Thanks for the information. The markers in our scenario are ~8m apart. 

I'd assumed that the interpolation was more of a weighted average than a triangular interpolation - I'll keep this in mind when we run the next test.

We're also (intentionally) using a space with poor tracking - a largely featureless carpark - to determine how WLT operates in this kind of environment.

I'll do a few things:
1. Double-check our code for QR and coordinate system transforms against the examples - we'd built it more against the QR samples than the WLT samples
2. Perform another 3D scan with the codes already in-place to assert that this is not a significant error source
3. Add the space pin visualizer
4. Record a video if the effect is significant enough to show up.

Hopefully it's just a result of (1) and the problem goes away :)

**Comment by fast-slow-still** [comment]
In case you are interested, the reason for triangular interpolation rather than something like a distance weighted average (which was the initial implementation) is that the triangular interpolation gives two very useful characteristics:
1. When you are *at* a SpacePin, the effects of all other SpacePins vanishes.
2. When you are between two SpacePins, only those two SpacePins have non-vanishing weights. 
 
For example, in your diagram, if you are midway between 4 & 6, then 2 should have no effect. And for that matter, if you are midway between 4&6, it's convenient that no other pins have any effect.

Anyway, that's the motivation behind the triangular interpolation rather than other possible weightings.

**Comment by camnewnham** [comment]
Thanks for the additional info. I've performed the above steps as planned and we weren't able to reproduce the issue - I suspect I made an error in working between the coordinate spaces of QR/Camera > Spongy > Frozen. The only discrepancies we saw in hologram positioning in this later test seemed to be drift in the intentionally poor tracking space which would largely correct once enough feature points were detected in an area..

The SpacePinVisualizer works very well to illustrate what's going on.

Another scenario - given a users position between 4 space pins, there are two ways in which it could be triangulated. 

In the following scenario, space pins 0,1,3 influence the interpolation.
![tri1](https://user-images.githubusercontent.com/19278856/107599913-3ff69f00-6c76-11eb-91a9-dc2249ce4d33.png)
However treating the triangle differently results in 0,1,2 influencing the interpolation from the same position.
![tri2](https://user-images.githubusercontent.com/19278856/107599916-4127cc00-6c76-11eb-84e3-f88afda2e1ae.png)

In general, I could see that a Delaunay triangulation makes sense (is this what WLT currently does?), but in some scenarios I could see the relationship between certain space-pins or axis being more important than others. While the space pin _should_ all be saying the same thing, in poor tracking scenarios the discrepancies seem to be greater.

This is largely a curiosity at this point - just getting my head around this while planning an implementation.

**Comment by fast-slow-still** [comment]
These are great thoughts, I appreciate you taking the time to share them. You are right about the ambiguity of the triangulation. WLT currently uses an approximation to Delaunay (in SimpleTriangulator in C#), but a more robust full Delaunay in C++ is in the works. The triangulation is only done when the set of active SpacePins changes, so while not deterministic whether you would get 0,1,2 or 0,1,3 above, whichever you got would be stable frame to frame.

Thanks again for the update!
