### ISSUE TITLE
[ISV] QR code under WLT snapping out of place after a loop closure

### ISSUE THREAD

**Issue by srinjoym** [microsoft/MixedReality-WorldLockingTools-Unity#236]
We have observed an issue where a QR code under frozen space jumps to the correct place after a loop closure then immediately jumps to the incorrect place

**Comment by fast-slow-still** [comment]
I haven't been able to repro this, and from your description it sounds like very application specific problem. If I understand correctly, the Space Pin placed by the QR code does end up in the correct place, but the QR code diagnostic/UX element (not sure which), which is not influenced by the space pin system, first moves to the correct position (on the refit operation) and then gets moved to an incorrect position.

Obviously I can only guess here, since I haven't seen the code, but it sounds like something on the application side might be thinking that it is keeping the QR code visualization in place, but is failing to take into account the effect of the refit operation, and so is actually moving the QR code to an incorrect position.

I would recommend putting diagnostics on the Space Pin, which winds up in the correct place, and the QR code, which winds up in the wrong place, and seeing when their global positions diverge.
