### ISSUE TITLE
Overriding the pose of the Hololens camera (question)

### ISSUE THREAD

**Issue by cellarmation** [microsoft/MixedReality-WorldLockingTools-Unity#34]
I am interested in understanding how WorldLockingTools overrides the normal Hololens tracking behavior in Unity. My understanding from a quick look at your [documentation](https://microsoft.github.io/MixedReality-WorldLockingTools-Unity/DocGen/Documentation/Concepts/BasicConcepts.html#world-locked-space) and [code](https://github.com/microsoft/MixedReality-WorldLockingTools-Unity/blob/6cd799f6c20415ecb1a9c87ad5e3d9deeb3ebca2/Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs#L493) is that you override the pose applied to the main camera by using a parent transform. The pose you ultimately want to use is the result of the calculations done in FrozenWorld, but to do that you also need to give it the [original camera pose](https://github.com/microsoft/MixedReality-WorldLockingTools-Unity/blob/6cd799f6c20415ecb1a9c87ad5e3d9deeb3ebca2/Assets/WorldLocking.Core/Scripts/AnchorManager.cs#L190) from the camera.

I have previously attempted to override the Hololens' automatic management of the Unity camera to apply a pose from an different tracking system using this sort of strategy. I found some issues with this sort of approach, and am interested in understanding if this is something you have observed or not, and if you were able to overcome it or not. 

I found that when the head was stationary this method worked very well, but during head movement (particularly head rotation) static world locked virtual objects would visibly judder. 
Ultimately my understanding was that the Hololens is doing some additional late stage re-projection, so the values you can access in a Unity script for the camera's pose are not really the _final_ values, so calculations in a normal script can't fully negate the pose that is being applied to the camera as there could be some delta movement late on that you don't get to know about. The comments in AnchorManager.cs state some uncertainty about if the pose from Camera.main.transform.local??? or InputTracking.GetLocal???(XRNode.Head) should be used, so I suspect you have had similar concerns? I believe I tried both API calls in the past and felt that neither made it possible to fully negate the original head pose. Could this be an issue for WorldLockingTools?

**Comment by VincentGuigui** [comment]
As you mentioned the camera is tied to the head movement/position detected by the sensors, so a local transformation (rotation/translation) is applied to a parent of the camera, preventing this jittering between conflicting transformations.

**Comment by fast-slow-still** [comment]
@VincentGuigui  yes exactly. But I’ll try to fill in more detail here.

@cellarmation rmation , yes you read that comment correctly. I have actually since found that, at that point in the update loop on the HoloLens, the Camera.main.transform.local??? is exactly equal to the InputTracking.GetLocal???(HRNode.Head) (and incidentally also equal to the new InputTracking.GetNodeState pattern for getting the head's Pose). I’ll open an issue to update that comment.

That sounds like interesting work you were doing earlier. I think the big difference between the camera tree manipulation in your work and in the WLT is that you were trying to negate the camera’s pose, whereas I am simply relocating it. A slight lag between the camera pose which you invert (to cancel out the pose) and the camera pose which is actually used for rendering will cause a visual judder as you saw. But I am not trying to cancel out the camera pose, I am simply giving it a new base coordinate space.

Of course, you are right in pointing out that the transform I compute and apply to the Adjustment node (grandparent of the camera) takes the current camera pose as an input, and thus creates the same feedback loop that led to your judder. However, the computed adjustment is both smoothly and gradually varying over space (which makes it smoothly varying over time as well as long as the camera position is smoothly varying. If the camera position is not smoothly varying, then its motion would mask any judder introduced). 

So in practice, as long as framerate is maintained at 60Hz or more, no judder is introduced.

**Comment by cellarmation** [comment]
@fast-slow-still this is great context and detail! Your comments have helped give me a bit more clarity around an investigation that I never really felt like I was able to bottom out. When I saw the WLT documentation state that the camera was being re-positioned I was hoping that there was some trick or magic API call that I had missed.

I am sure your analysis of the situation is correct, the two use cases are different and I can see how WLT is not fighting the camera management to the same extent that I was. I am very impressed that this project has been realised within the existing constraints. I look forward to trying the library out, thank you.
