### ISSUE TITLE
Multi-User Experiences

### ISSUE THREAD

**Issue by BastiaanGrisel** [microsoft/MixedReality-WorldLockingTools-Unity#39]
Hi all,

Thanks for this great package! It works out of the box in an existing project and it's quite magical. 

I would love to be able to use this to synchronise the virtual environment across multiple Hololenses. Would this be possible? 

I guess the easiest thing to so is to somehow distribute the Saved Frozen State to all users at the start of a session. Can I somehow access the raw/serialized data that `WorldLockingManager.GetInstance().Save();` saves in order to accomplish this? 

Cheers,
Bastiaan

**Comment by fast-slow-still** [comment]
Hi Bastiaan, and thanks for the kind words!

The shared experience is very important to us, and is an area of active development. We are working through several scenarios with customers, and hope to post back samples soon showing successful strategies.

While capturing and sharing the serialized Frozen State across devices would be possible, I’m afraid it wouldn’t accomplish what you want. That’s because the state is dependent on the associated persisted WorldAnchor’s. While it would be theoretically possible to share the WorldAnchor network across the devices, in practice we’ve found that trying to share more than one or so WorldAnchors is prohibitively expensive.

Two very promising strategies we are investigating start off similarly to each other. In both cases, you start off with the world-locked space as seen in the WorldLockedPhysics sample (i.e. the most basic, drop the WorldLockingContext prefab in the scene and setup the camera hierarchy appropriately).

Both strategies then align each device’s independently world-locked coordinate space via a small number of shared reference “markers”, which feed into the Space Pin subsystem.

The first strategy gets reference positions from Azure Spatial Anchors, which are by definition shareable. The poses from the shared ASA align the coordinate spaces on the different devices with the same physical space.

The second strategy gets reference positions from QR code printouts in the physical environment. These again feed into the Space Pin subsystem. Because each device is (independently) aligning to the same physical markers, the coordinate systems on all devices are aligned.

I’m afraid I don’t have any code to share at the moment, but wanted to share our thinking on this as early as I could.

**Comment by BastiaanGrisel** [comment]
Thanks for the detailed response! Very cool to hear your strategies and looking forward to seeing when you are able to share more. 

Of course it would be great to get the initial alignment to work with Azure Spatial Anchors for maximum magic but I guess the QR-code strategy is a tad easier to code/debug. The QR codes would probably only need to be shown at the beginning of the experience?

I'll stick to using WorldAnchors for my projects at the moment.

**Comment by fast-slow-still** [comment]
That is correct that the QR codes would only be needed at startup. Because the underlying FrozenWorld technology is keeping the coordinate space fixed relative to the physical world, the Space Pins are only needed once to establish correspondence(s).
