### ISSUE TITLE
Performance/area limitations

### ISSUE THREAD

**Issue by zantiu** [microsoft/MixedReality-WorldLockingTools-Unity#61]
First of all thanks for writing this package. It does not seem to get too much attention yet, but that's probably just a matter of time since the concept is fundamental in making making bigger and seamless AR experiences.

I did a quick test with HL2 in a relative big area and ended up with a anchor count of about 500. At that moment the framerate had dropped to about 30FPS with marker and mesh visualizations switched off.

Have you been testing with bigger areas and what are your experiences?

Would it be an option to reduce the processing intensity for anchors if they are further away, maybe totally disabling above a certain range?

Do you think WorldLockingTools would be able to scale to huge interior spaces, let's say airport terminals? And what would need to happen to make this feasible?

**Comment by fast-slow-still** [comment]
That's a larger area than I have been able to test in, but your numbers seem consistent with extrapolating from larger area tests that I have done (maxing out at about 150 anchors).

Again extrapolating from performance testing I've done, it has appeared that when getting over 100 anchors, the performance cost is dominated by the Unity WorldAnchors themselves. The processing that WLT does on them is negligible in comparison. 

I like your idea of limiting the distance range of WorldAnchors, as those very far away aren't contributing to the world-locking anyway.

Consider this option:

Client specifies a maximum range from camera for active WorldAnchors (or possibly maximum count?).

As the user moves to a new area, most distant WorldAnchors are discarded completely, as new WorldAnchors are created to populate the new space. When moving back to the discarded area, new WorldAnchors would again be created to populate it.

This eliminates both the Unity WorldAnchor performance cost, and the WLT anchor processing cost for those distant anchors, effectively capping the WLT performance cost.

This has implications for persistence, which I haven't thought through. It may have other side-effects which haven't occurred to me yet.

But overall I am liking the idea. Does it sound like it would suit your needs? Or are there requirements that you have that you can think of which would be broken by this?

Thanks for your thoughts!

**Comment by fast-slow-still** [comment]
Also, and orthogonal to the above, there is a parameter which determines the density of WorldAnchors created. It currently targets about 1m separation. For very large spaces, that is probably much more dense than necessary. I need to verify that, but should at least make the parameter publicly available on the WorldAnchorContext for easy experimentation.

**Comment by fast-slow-still** [comment]
I am liking your idea more and more.

Thinking about it more, I think it would be significantly better to make it a graph distance, rather than a spatial distance. That is, distance along the edges of the graph maintained by the AnchorManager. For example, WorldAnchors in an adjacent room might be closer spatially, but less relevant than WorldAnchors in the farther reaches of the current room. 

Also, I more and more like capping the number of active anchors, rather than a distance. A cap on the number of anchors puts an actual limit on the compute used by WLT. The same number of anchors distributed along a series of hallways would have a much farther reach than a dense network in a large space, but would have the same compute usage.

**Comment by zantiu** [comment]
Yes please expose AnchorDistance.

Discarding world anchors could be an option.
Another option could be to save them and reload later.

About absolute vs graph distance: not sure if graph distance is always a good idea. It's not because there's no physical path to something that it can't be seen.

Yes the goal is to keep the amount of active anchors limited to keep performance up. But maybe that number also needs to be configurable, maybe even allow adjustments during runtime.

Also this kind of use cases will be multi-user and persistent so maybe attachment-points need to be part of the strategy.

Maybe it makes sense to make a sample that tries to scan qr codes in the environment, and if found automatically created an attachment point. Then as you move away the anchors around this area get forgotten, and when coming back by scanning the qr code the virtual coordinate system can be synced again to the previous position. Does that make sense?

**Comment by fast-slow-still** [comment]
Good thoughts. I'll do some quoting to address specific issues you bring up, which all seem important enough for discussion.

> Yes please expose AnchorDistance.

Done, available now in master branch, also in release getting posted today (or ASAP). See AnchorSettings in [WorldLockingContext.SharedSettings](https://microsoft.github.io/MixedReality-WorldLockingTools-Unity/DocGen/Temp/api/Microsoft.MixedReality.WorldLocking.Core.WorldLockingContext.html#Microsoft_MixedReality_WorldLocking_Core_WorldLockingContext_SharedSettings).

> Discarding world anchors could be an option.
Another option could be to save them and reload later.

The interesting thing here is, what would be preferable about the WorldAnchors saved and then reloaded, versus brand newly created WorldAnchors? The main difference would be the performance penalty for the saved then loaded. But these WorldAnchors are placed more or less arbitrarily to fill a space. So there's really nothing special about an old WorldAnchor to save, that can't be replaced by a brand new WorldAnchor. 

> About absolute vs graph distance: not sure if graph distance is always a good idea. It's not because there's no physical path to something that it can't be seen.

Agreed that graph distance might not always be ideal. But I would argue that it is generally preferable. First, because a WorldAnchor position can be seen doesn't mean that it is relevant, or that it will be soon relevant.

The idea here is that WorldAnchors in the general vicinity of the tracker are useful. All other WorldAnchors exist only because they will become useful if the tracker moves into their vicinity.

Graph distance isn't a good indicator of visibility, but it is the best indicator we have of reachability, which is more relevant than visibility.

Consider 3 clusters of anchors, A, B, & C. Distance |AB| == |BC| == |AC|/2. So it is half the distance from A to C than from A to B or from B to C. However, there is no way to get from A to C without going through B. That last point is indicated by there being graph edges between A and B and between B and C, but no graph edges between A and C.

A and C might be perfectly visible from each other, but if I am at A, then the anchors in B will become relevant before the anchors in C do, because I have to go through B to get to C. And regardless of visibility, the anchors in C will not be useful while I am in A. 

> Yes the goal is to keep the amount of active anchors limited to keep performance up. But maybe that number also needs to be configurable, maybe even allow adjustments during runtime.

Agreed fully.

I'm afraid I got lost in the last two paragraphs. Perhaps by "attachment points" you meant "space pins"? If so, apologies about the naming. And issues filed about confusing parts of the documentation, or gaps in the documentation, are very much appreciated!

Thanks again for this discussion, I am finding it quite interesting and, hopefully, useful.

**Comment by zantiu** [comment]
>The interesting thing here is, what would be preferable about the WorldAnchors saved and then reloaded, versus brand newly created WorldAnchors? The main difference would be the performance penalty for the saved then loaded. But these WorldAnchors are placed more or less arbitrarily to fill a space. So there's really nothing special about an old WorldAnchor to save, that can't be replaced by a brand new WorldAnchor.

I'm not an expert in WorldAnchors, but isn't it like this that the loaded WorldAnchors continuously try to detect their location in the real world? (which would explain the big performance drop when using many of them) And WorldLockingTools (WLT) also attaches a WorldAnchor to a fixed coordinate.  So if you come back to a WorldAnchor that was previously distant and it gets recognized you know the fixed WLT coordinate. Now if you would start creating new WorldAnchors because you didn't save them then you're basically rediscovering this area, and the WLT coordinates will not longer be the same as before.

For a practical example: imagine there's a chair in a big space and you drop a sphere right on top of it. Then you walk away for a long distance and forget the anchors. As you walk back the WLT coordinates will have shifted unless if you reload the previously saved anchors. And if the WLT coordinates have shifted then the sphere will not be longer on top of the chair.

Not sure if this reasoning is correct? And ofcourse the performance hit of saving and reloading world anchors will need to be considered if we can't do without.

**Comment by zantiu** [comment]
> Agreed that graph distance might not always be ideal. But I would argue that it is generally preferable.

I think the optimization of the distance calculation algorithm is probably of lower importance for now. I suggest pick something that feels workable and implement in a way that it can be easily adjusted later. Maybe even allowing a selection between different strategies to quickly test in different situations.

**Comment by zantiu** [comment]
> I'm afraid I got lost in the last two paragraphs. Perhaps by "attachment points" you meant "space pins"?

It's a concept in WLT: https://microsoft.github.io/MixedReality-WorldLockingTools-Unity/DocGen/Documentation/Concepts/Advanced/AttachmentPoints.html

For example you can use this when there are QR codes in the space that always need to have the same WLT coordinates if my understanding is correct.

Going back to the example with the sphere on the chair: if there's a QR code on the chair then this would also help keeping the sphere on the chair if you put an AttachmentPoint on it. I am not convinced that QR codes are sufficient by itself, because if you always have to rely on QR codes then you might need too many of them, and you also continuously need to scan them. But I think it will be needed for an initial scan of the space where the coordinates for all users need to be the same.

Again the sphere on the chair example:
- multi-user means all the users see the sphere on the chair
- persistent means when auser reloads the application the sphere will still be on the chair (assuming someone put it there in a previous session)

Of course this kind of shared and persistent experiences by itself should not be part of WLT, but the way that WLT is set up should allow developers to use it to create this kind of experiences based on a fixed coordinate system anchored to the real world with AttachmentPoints.

(QR codes can also be replaced by Azure Spatial Anchors or other methods to determine positions in the real world.)

**Comment by fast-slow-still** [comment]
> Of course this kind of shared and persistent experiences by itself should not be part of WLT, but the way that WLT is set up should allow developers to use it to create this kind of experiences based on a fixed coordinate system anchored to the real world with AttachmentPoints.
> 
> (QR codes can also be replaced by Azure Spatial Anchors or other methods to determine positions in the real world.)

You should definitely have a look at this sample from the sibling Samples repo.

https://microsoft.github.io/MixedReality-WorldLockingTools-Samples/Advanced/QRSpacePins/QRSpacePins.html

**Comment by zantiu** [comment]
Thanks for pointing out that example, I didn't notice there was a separate repo with more advanced examples. I tried it and it seems to work.

So to conclude: the main feature request to make WLT usable in big spaces is removing remote anchors in a way that minimizes the performance impact.
Is that something that could be added to the roadmap?

And maybe optionally: instead of removing the anchors completely they could be saved and reloaded if that makes sense and doesn't create other performance penalties.

**Comment by zantiu** [comment]
Another thing that I have been wondering is how the Hololens OS manages the environment when not in an app. Because the windows of all opened apps stay nicely where they were before, also between sessions. So is Hololens OS also putting anchors all over the place, and reloading them during the next session?

**Comment by fast-slow-still** [comment]
> So to conclude: the main feature request to make WLT usable in big spaces is removing remote anchors in a way that minimizes the performance impact.
Is that something that could be added to the roadmap?

I'll consider this open issue to be the public work item to that end.

**Comment by zantiu** [comment]
Sounds good!

**Comment by zantiu** [comment]
Hello @fast-slow-still Did this end up on the roadmap?

**Comment by fast-slow-still** [comment]
Yes it did. I was hoping to have it in the next release (within the next week) but am not sure it will make it. But it is a high priority area, and will probably be available before the mobile platform support (which is also imminent).

**Comment by zantiu** [comment]
Ok not super urgent be we plan to use it in a pilot around a production line in a couple of months, so it will be very useful!

What do you mean by mobile platform support? iOS and Android? Because that would be great. It would probably open up the possibility for spectator view again for us.

**Comment by fast-slow-still** [comment]
Great, yes, I still agree that dealing with large spaces efficiently is of utmost importance.

Yes, on Unity XR SDK. I have a version up and running on Android, but it still needs a lot of work to be production quality.

If you are interested, I can let you know when I have a branch with quality worth previewing.

**Comment by zantiu** [comment]
Yes large spaces and also spaces with multiple levels.
I think there was another topic discussing that already.

Yes please keep me updated about the progress!

**Comment by zantiu** [comment]
How is the progress for the mobile support? Anything that could be used for a preview?

**Comment by fast-slow-still** [comment]
Closing this issue until the current baseline solution can be analyzed for effectiveness. With that knowledge, we can iterate on making this more effective. See further notes in #94.
