### ISSUE TITLE
Rotation irrelevant when creating than one SpacePin?

### ISSUE THREAD

**Issue by zantiu** [microsoft/MixedReality-WorldLockingTools-Unity#77]
Just a quick question for verification:

We noticed we were feeding correct positions but completely wrong rotations when creating new SpacePinPackages.
(Positions coming from scanned qr codes.)
But the positioning of the holograms still worked well.

Does that mean that the rotations of the virtualObject passed to SpacePinPackage.Create() don't matter anymore once there's more than one SpacePinPackage?
That would make sense because rotation inferred from two points will be more accurate than rotation from a scanned QR code.

Also it normally takes 3 points to define the rotation of a coordinate system. But I assume you only need two points because you always keep the Y-axis vertical?

**Comment by fast-slow-still** [comment]
You are correct on both. This is if you are using SpacePinOrientable (recommended). 

If you have only submitted one SpacePinOrientable with SetFrozenPose(), the rotation submitted is used.

With two or more SpacePinOrientables, and an Orienter, the submitted rotation is ignored and the rotation about the Y axis implied by the relative positions is used. This assumes the you want your gravity vector (Y-axis) preserved.

With three or more SpacePinOrientables, you can fully define an arbitrary rotation. To do this, you need to use an OrienterThreeBody, instead of the base Orienter.

**Comment by zantiu** [comment]
Ok thanks. Yes in most practical applications it will be desirable do put the Y-axis on the gravity vector.
